### ISSUE TITLE
Cannot use within a flow embedded in a public digital experience

### ISSUE THREAD

**Issue by boutiqueorchard** [SFDC-Assets/DynamicFlowProgress#4] opened 2022-03-03 19:22 UTC
Experiencing similar issues as previously stated. Is this use case intended and if so, is there any available support?

The component displays as expected when using the flow debug.

**Comment by egyptguy** [comment] 2022-03-06 13:58
Duplicate of #3

**Closed by egyptguy** 2022-03-06 13:58 UTC
